### ISSUE TITLE
How to Manually Add Route (Help with)

### ISSUE THREAD

**Issue by biomade** [baseljs/basel#10]
I see in the app.js there is commented code , so I uncommeted it 
```
//For new routes:
    	$routeProviderReference.when('/when',{
	 		controller: 'test',
	 	   templateUrl: 'views/test.html'
        })
```
I then created a test controller similar to the example controller and I also added a test.html page based upon the example.html. 
In the index.html I added in the script tag for the new controller

`<script src="controllers/testController.js"></script>`

and in the menu div's I added a new list item and commented out the items from the database
```
<ul class="nav navbar-nav">
  <li ng-repeat="menu in menus">
     <!-- <a href="#/{{menu.route}}">{{menu.name}}</a> -->
 </li>
 <li >
   <a href="#/test">Test</a>
 </li>
</ul>
```
I can't get this route to load. When I change the href in my menu item to example, the example route/page will load.   Can you tell me what I am missing or is adding manual routes not possible

**Comment by jayralencar** [comment]
You can see errors in the console?

**Comment by biomade** [comment]
No, nothing happens. But a am new at this so I could be missing something.
Does it appear I have things correct?

I can post a link to my repo if you want. Let me know

Thanks so much

sent from Agnes the android phone

**Comment by jayralencar** [comment]
Show me the content of testController please.

**Comment by biomade** [comment]
Will do when I get to work in about 2 hours

sent from Agnes the android phone

**Comment by biomade** [comment]
Here it is 

```
"use strict";
app.controller("testController", function($scope, $location){
	console.log("in test controler")
});
```

**Comment by jayralencar** [comment]
Try:
```
 $routeProviderReference.when('/when',{
	 		controller: 'testController',
	 	   templateUrl: 'views/test.html'
        })
```

**Comment by biomade** [comment]
will do later today. Thanks

**Comment by biomade** [comment]
nope, the page still does not load, the controller does not write a message to the console window

**Comment by jayralencar** [comment]
```
$routeProviderReference.when('/when',{
	 controller: 'testController',
	 templateUrl: 'views/test.html'
});
```
Look. In the example above your route is "/when", so you have to use this path in your href in the menu, or modify your route to "/test"

**Comment by biomade** [comment]
ohhh, I get it now, let me try this

**Comment by biomade** [comment]
Now it works. Thanks so much. Might I suggest you update the commented out code for the manual route to refelect that all three items match the same name and also add the views/ to where the views are located.

**Comment by biomade** [comment]
Maybe you add this. 
//For new routes:
    	$routeProviderReference.when('/test',{
			controller: 'testController',
		  templateUrl: 'views/test.html'
       })
