### ISSUE TITLE
How to do a route with a parameter [Question - How to]

### ISSUE THREAD

**Issue by biomade** [baseljs/basel#12]
I have a route named "person"  and the person.html page has the list of all people in the database. I have modified the edit button in the person row of the list to now call a new function which will (should ) display the details for that person.

I have created the personDetail route/view/controller via the basel-crud cli. 

I am passing the item selected on the person.html,  into the function in the personController as shown.  
```
$scope.changeView = function(item) {
    $location.path("/personDetail"); //this will load the personDetail page no problem
    //$location.path("/personDetail/" + item.id); //this does not load the personDetail. 
  }
```
How can I get this new route (ie: /personDetail/1) to actually route to the personDetail page.

**Comment by jayralencar** [comment]
Create a route to personDetail/:id

**Comment by biomade** [comment]
I updated the route in the crud table and it works. thanks so much, again
