### ISSUE TITLE
Cancel in Modal Popup leaves changes in list

### ISSUE THREAD

**Issue by biomade** [baseljs/basel#13]
I was testing a change to an item using the edit (modal) form. 
If you change any field, the change is immediately shown in the list, behind the modal form (which will happen because both are bound to the same item model. 

BUT if you click the cancel button to close the modal form, the change is still in the list which should not happen because the save button was not clicked. 

I made this change in the controller cancel function and now the list re-displays the valid data. 
You might want to implement this change or should I try to do it myself (I have never done that to someone else's code!) 
```

  $scope.cancel = function() {
    //$scope.form = {};
    //this will refresh the page without the changes
    $scope.list();
  }
```

**Comment by jayralencar** [comment]
Yes, you can do it.

**Comment by biomade** [comment]
Thanks, I have cloned the repo to my machine and added a branch. I can't submit it via a pull request. I think you need to add me to the project
