### ISSUE TITLE
Can not get the error messages back from the db.

### ISSUE THREAD

**Issue by biomade** [baseljs/basel#15]
Inside the generated controller, the  save function has this function call to insert a new record: 
` basel.database.insert($scope.table_name, $scope.form);`
and the update is: 
```
basel.database.update($scope.table_name, $scope.form, {
        id: id
      });
```

How can I access an error message that is returned from the database.

**Comment by biomade** [comment]
resolved - I just have to add a variable to get the response

var msg = basel.database.update($scope.table_name, $scope.form, {
        id: id
      });

**Comment by jayralencar** [comment]
Use assync.
