### ISSUE TITLE
Question: Nesting tabs within the Index.html

### ISSUE THREAD

**Issue by biomade** [baseljs/basel#18]
I am looking at the base Basel project and the Index.html display the other views within the following tag:
` <div ng-view="" class="container"></div>`
I am wondering how i can have  another views display tabs, and each would then have a partial view.

For example I only want two menu items. People and Workshops. 
The People.html page would list people in the people table. 
When I click a button on a person row, it displays a Person.html view, and on this page it has 4 tabs: Email, Phones, Address, Other. 

Then if you click a tab, you get to see the information for that partial view. 

Is this possible?  
Would the routes, for each tab then load that partial view OR do I have to have a route for each tab, and in those views code up the tabs but only display  the infor for that tab. 

Thanks in advance for all your help

**Comment by jayralencar** [comment]
You have to use angular's eventemitter

**Comment by biomade** [comment]
Thanks, I will read up on it.
