### ISSUE TITLE
packager problem

### ISSUE THREAD

**Issue by godhand4826** [baseljs/basel#22]
I try to clone the project and pack the app. 
```
$npm install basel
$./node_modules/basel/bin/basel-init.js SOME_APP
$cd SOME_APP/
$npm install
$npm start    
```
works fine till here, but ...
```
$npm run win64
$cd  myApp-win32-x64/
$./myApp.exe
```
It can execute but the angular seems not work, the title of the app is **{{app.title}}**.
I guess the reason is the **electron-packager** do not include **module/database.db** while packing.

**Comment by jayralencar** [comment]
Move model/database.db to your executable's folder.
