### ISSUE TITLE
Cannot Pack Basel

### ISSUE THREAD

**Issue by fawwaz** [baseljs/basel#3]
I just clone your git, install node dependencies with npm. I also tried to make a crud with `basel-crud` and it successfully create the `model/database.db` file. Then, i tried to package it with this command :
`electron-packager . myApp --platform=win32 --arch=x64` ,  Although it successfully create `myApp.exe` however, once i run the produced executable, the aps showed a problem as below : 
![ini](https://cloud.githubusercontent.com/assets/1295143/15585210/80c35a9e-23a8-11e6-8a63-3aef59a736b4.JPG)
I guess it failed to load angular js, what should i do to fx this ?

**Comment by jayralencar** [comment]
Put the file basel.json in the executable 'sdirectory.

**Comment by fawwaz** [comment]
I've copy the basel.json to executable's directory  (see this image) ![ini](https://cloud.githubusercontent.com/assets/1295143/15601509/efb14832-2419-11e6-9596-e2a83d33d850.JPG) However, it not solve at all.

**Comment by jayralencar** [comment]
Put the folder model  in the executable's directory.

**Comment by fawwaz** [comment]
Thank you ... it works .. yes the solution is puting the model folder inside executable's directory. However, the next question is what should i do if i want to make an installer for my executable ?

**Comment by kuldeep349** [comment]
![image](https://user-images.githubusercontent.com/24997363/34902896-3ca262c8-f84b-11e7-99b6-24cda227c56e.png)

i have placed model folder and pakage.json file inside the folder but still facing same issue .
Please help me
