### ISSUE TITLE
Problem creating the project

### ISSUE THREAD

**Issue by javiergrande** [baseljs/basel#4]
Hello developers . I am new to the world of nodejs and I could not run basel- init . Install through npm but the next step to execute "init -base newapp " I get a warning "file or directory not found."

Thank you

**Comment by jayralencar** [comment]
Hi @javiergrande 
Tell me your system configurations.

**Comment by javiergrande** [comment]
Hello @jayralencar. I'm using Linux Mint 17.3 64 bit, node v6.1.0 and npm v3.10.3.

**Comment by jayralencar** [comment]
Ok, you have to use:
**basel-init new app**
And not
"init -base newapp "

**Comment by javiergrande** [comment]
Sorry the translator corrected me wrong. I did the steps detailed but still the same.
You need to have installed some other package apart from basel?

Thank you

**Comment by jayralencar** [comment]
@javiergrande 

Look it: [http://clubedosgeeks.com.br/programacao/node-js/app-desktop-basel-framework#comment-3800](http://clubedosgeeks.com.br/programacao/node-js/app-desktop-basel-framework#comment-3800)

**Comment by javiergrande** [comment]
Thank you very much for your help. I solved the problem. I make a query, the sqlite is integrated into the browser chromium (electron)?

**Comment by jayralencar** [comment]
SQLite Interation: [sqlite-sync.js](https://github.com/jayralencar/sqlite-sync.js), [sqlite-cipher.js](https://github.com/jayralencar/sqlite-cipher.js)
