### ISSUE TITLE
Question: how to make an express app from a basel app

### ISSUE THREAD

**Issue by gbrault** [baseljs/basel#6]
Thanks for your work!
Would be glad to have some guidance to have both the application working with electron and with express as well?

**Comment by jayralencar** [comment]
Hi @gbrault , basel does not work with express. 
But, you can create a app with electron and express.

**Comment by gbrault** [comment]
Thanks for your answer!
What I would like is to use the application "generated" by basel into express.
Is that possible?

**Comment by jayralencar** [comment]
Not yet, but can be developed after.

**Comment by gbrault** [comment]
Any idea about your timing?
